# Generated by Django 3.2.8 on 2021-11-26 20:07

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipexterno',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
