# Generated by Django 3.2.8 on 2021-12-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_ipexterno_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipexterno',
            name='porta',
            field=models.CharField(max_length=5),
        ),
    ]
