# Generated by Django 3.2.8 on 2021-12-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_ipexterno_porta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipexterno',
            name='porta',
            field=models.IntegerField(),
        ),
    ]
